# Generated by Django 3.0.7 on 2020-07-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='GshhsteJN2FZ17Nhndy3qtDIoDw6t3W03XwaThbLJLkSfyxWMLxudhWvyw1LBLEVmpJZsicpd9xBdzXB1SPEW7IshM', max_length=250, unique=True, unique_for_date='publish')),
                ('story', models.ImageField(upload_to='stories/%Y/%m/%d')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_story', to=settings.AUTH_USER_MODEL)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='catagories.Categories')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
