# Generated by Django 3.0.7 on 2020-07-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200701_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='pwucCkSRWWoriqk9YYMeo0ofrsr36Mj7mMHyu6vzkMFgDiDakCx5V3SSa8PM7xafVGldY9AICvD6VfyKpyS7r5K1cI', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
