# Generated by Django 3.0.7 on 2020-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200614_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='NnZXi73iiOM0MdDzh0Wj', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
