# Generated by Django 3.0.7 on 2020-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200623_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='1cqWltMAM9wGeiWXzY64', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
