# Generated by Django 3.0.7 on 2020-07-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200711_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='mjvzn5u8kWxlpmYiHmYQjbIW1Grrsv4QegowKP4zOyTqpjbb6bw3NT6xTKsW1HoWX2fMtHLxsPGRKxbHgisyNKQUx2', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
