# Generated by Django 3.0.7 on 2020-06-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
        ('stories', '0005_auto_20200623_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='catagories.Categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='aKCkAXP48z4MLtsWRiUe', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
