# Generated by Django 3.0.7 on 2020-07-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200717_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='Pilm1m1B4bXqsDkC1MkoCcwTlIXZmSKoo0e5xG92bByUIjzIdcIyHBQcKQPqdndJAHd4v6SwFRPltGjbm4CuTxMv4M', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
