# Generated by Django 3.0.7 on 2020-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200624_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='hb5ydHVJjvr0MQdrhvKv', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
