# Generated by Django 3.0.7 on 2020-06-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
        ('stories', '0009_auto_20200624_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='catagories.Categories'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='6gemPwVP7kRs8ClL11Cl', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
