# Generated by Django 3.0.7 on 2020-06-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20200624_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='category',
            new_name='categoryid',
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='haFz3cL0oCM5DCWXWb8d', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
