# Generated by Django 3.0.7 on 2020-06-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
        ('stories', '0011_auto_20200624_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='catagories.Categories'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='UzhDxjnn9A1Bpr3eVupt', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
