# Generated by Django 3.0.7 on 2020-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20200624_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='l0KzIZiy38mEZcp8hRL2', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
