# Generated by Django 3.0.7 on 2020-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20200629_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='8GNb8n2SMmX3w8f7p1eb', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
