# Generated by Django 3.0.7 on 2020-07-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='IfMdsv9gev0i69FkPjaEbeJ602px2znivezhXfAn8Dnl3PI7WwNiRzdHATV4wz5lGeggBXLX3yWMd3ouWQfALsNbKq', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
