# Generated by Django 3.0.7 on 2020-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='JmQFoz', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
