# Generated by Django 3.0.7 on 2020-07-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200701_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='TKKjNFjEkkNatnB0Hpyi7Ylm2NBYUKiFKoXnXA5BigPAK89KLVtfGWWc7yKgyySV88DqaA24o254hLIWPkwzJk7F8s', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
