# Generated by Django 3.0.7 on 2020-07-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200711_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='U6wt2tuKY95EwSo4Wd9R4rMpl2WMnIFKaW8zRZRQBSm2QL1pP72AbjctA2qTBWNa0va83sGUeh3owcDnOGQN3OcC7w', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
