# Generated by Django 3.0.7 on 2020-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200619_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='LMti20', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
