# Generated by Django 3.0.7 on 2020-07-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200716_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='wz3diNFUuntQq8hXeQzMchIs5l1LYDWn56wZEByDr8z9oEWmEaFyZIMVrryVRspQsiD1p9Cwck55UI2cNJDSBfiYnu', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
