# Generated by Django 3.0.7 on 2020-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200619_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='NSUW8XLFkxM58YrARCIw', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
