# Generated by Django 3.0.7 on 2020-07-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200717_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='HC1jxKcJuowQY56AjMPKGvh9TLiXOxhuzM5SCi2X8IhFo657tPtkKwpPdEx3PSXGiWIpXeIAQEVDP8VXqRzu8zFmfG', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
