# Generated by Django 3.0.7 on 2020-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200623_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='xMzGCgNdIuU1wDSy1nLC', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
