# Generated by Django 3.0.7 on 2020-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20200623_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='XqYFsMNrCqF2CKfBNdMF', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
