# Generated by Django 3.0.7 on 2020-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20200623_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='QGMQ5njqw6R9nTb7FSlc', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
