# Generated by Django 3.0.7 on 2020-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20200624_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='kHSPr5qGN8vFAIpUkFWq', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
