# Generated by Django 3.0.7 on 2020-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20200624_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='9OC6gpdoGEXAwn42M24y', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
