# Generated by Django 3.0.7 on 2020-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20200624_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='HT6kN8VXW2veMYG1W4is', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
