# Generated by Django 3.0.7 on 2020-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20200624_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='MBonCK3mOM3rIN0j4ai1', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
