# Generated by Django 3.0.7 on 2020-06-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
        ('photos', '0014_auto_20200624_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='categoryid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='category_photo', to='catagories.Categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='1i84JGL581yFCgd48zPq', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
