# Generated by Django 3.0.7 on 2020-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_auto_20200624_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='RTSl2cqaDJ9xwFp7T1l8', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
