# Generated by Django 3.0.7 on 2020-06-30 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0016_auto_20200629_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='Ooo65DS23I85ayvtqhHn1PLSTo6R3R6cwEux9NECeAw6gXnG5sljTo5eP1uz6etpUNLswe0ksZHpyqJN7nEPi0qOu0', max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
